# Single-file artifact: bundle src/main.js (sprites included), inline it into game2d.html.
import re, subprocess, json, sys
from pathlib import Path
os_root = Path(__file__).resolve().parents[1]
import os
os.chdir(os_root)
live = "--live" in sys.argv
# CI keeps its fresh Playground beside ignored build scratch.
output = Path(sys.argv[sys.argv.index("--output") + 1]) if "--output" in sys.argv else Path("artifact-2d.html")
subprocess.run(["python3", "-c", "d=open('bake/sprites.json').read();open('src/bake-data.js','w').write('export default '+d+';\\n')"], check=True)
# the mods bundled with the page (?mod=<id>): mods/*.json, as data (the page never fetches a mod)
import glob, os
mods = {}
for f in sorted(glob.glob("mods/*.json")):
    m = json.load(open(f))
    mods[m["id"]] = m
open("src/mods-data.js", "w").write("// generated by tools/build.py from mods/*.json: the mods bundled with the page (?mod=<id>)\nexport default " + json.dumps(mods, ensure_ascii=False) + ";\n")
chk = subprocess.run(["node", "tools/validate-mod.mjs", *sorted(glob.glob("mods/*.json"))], capture_output=True, text=True)
print(chk.stdout.strip())
assert chk.returncode == 0, "a bundled mod does not validate"
entry = "src/main.js"
if live:
    entry = "src/main.live.js"
    Path(entry).write_text('import "./live-entry.js";\n' + Path("src/main.js").read_text())
try:
    subprocess.run(["bun", "build", entry, "--format", "esm", "--minify", "--outfile", "build/v2d.bundle.js"], check=True)
finally:
    if live:
        Path(entry).unlink(missing_ok=True)
js = open("build/v2d.bundle.js").read().replace("</script", "<\\/script")
html = open("game2d.html").read()
head = html.split("<head>", 1)[1].split("</head>", 1)[0]
body = html.split("<body>", 1)[1].split("</body>", 1)[0]
head = re.sub(r'<meta name="viewport"[^>]*>\s*', "", head)

inline = "\n" + js + "\n"
body = body.replace('<script type="module" src="./src/main.js"></script>', '<script type="module">' + inline + "</script>")
# the CSP: the one inline script, by its hash (and nothing else may run)
import hashlib, base64
sha = base64.b64encode(hashlib.sha256(inline.encode()).digest()).decode()
assert "script-src 'self'" in head, "the CSP is in game2d.html"
head = head.replace("script-src 'self'", "script-src 'sha256-" + sha + "'")
for d in ["connect-src 'self'", "object-src 'none'", "base-uri 'none'"]:
    assert d in head, "the CSP keeps " + d
assert "./src/" not in body, "a local reference is left"
for bad in ([] if live else ["fetch(", "EventSource", "XMLHttpRequest", "WebSocket", "sendBeacon", "importScripts"]):
    assert bad not in js, "network call in bundle: " + bad
out = head.strip() + "\n" + body.strip() + "\n"
if live:
    # The board uses system fonts. Live adds no third-party origin or font request.
    out = re.sub(r'<link[^>]+https://fonts\.[^>]+>\s*', '', out)
    out = out.replace(" https://fonts.googleapis.com", "").replace("font-src https://fonts.gstatic.com", "font-src 'self'")
    out = '<!doctype html>\n<html><head>' + out.split('<style>', 1)[0] + '<style>' + out.split('<style>', 1)[1]
    # The artifact convention omits document wrappers; Live serves a complete page.
    out = out.replace('</style>', '</style></head><body>', 1) + '</body></html>\n'
    target = os_root.parents[1] / "board/public/voyage2d/index.html"
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_suffix('.tmp')
    temporary.write_text(out)
    temporary.replace(target)

else:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(out)
hosts = sorted(set(re.findall(r"https?://([a-zA-Z0-9.-]+)", out)))
print(len(out.encode()), "bytes; hosts:", hosts)
